
/*
 * generated by Xtext
 */
 
package fr.chaunier.xtext.bom.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class BomDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return fr.chaunier.xtext.bom.ui.internal.BomDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return fr.chaunier.xtext.bom.ui.internal.BomDslActivator.getInstance().getInjector("fr.chaunier.xtext.bom.BomDsl");
	}
	
}
