/*
 * generated by Xtext
 */
package fr.chaunier.xtext.omcst.om.scoping;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class OmcstDslScopeProvider extends AbstractDeclarativeScopeProvider {

/*	
	@Override
	public IScope getScope(EObject context, EReference reference) {
		System.out.println(
				"OnCst: scope_" + reference.getEContainingClass().getName() + "_" + reference.getName()
				+ "(" + context.eClass().getName() + ", ..)"
			);
		return super.getScope(context, reference);
	}
*/
}
