/*
 * generated by Xtext
 */
package fr.chaunier.xtext.path.map.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PathDslUiModule extends fr.chaunier.xtext.path.map.ui.AbstractPathDslUiModule {
	public PathDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
