/*
* generated by Xtext
*/
package fr.chaunier.xtext.omc.ui.contentassist;

import fr.chaunier.xtext.omc.ui.contentassist.AbstractOmcDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class OmcDslProposalProvider extends AbstractOmcDslProposalProvider {

}
