/*
* generated by Xtext
*/
package fr.chaunier.xtext.omcst.om.ui.labeling;

import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class OmcstDslDescriptionLabelProvider extends DefaultDescriptionLabelProvider {

	//Labels and icons can be computed like this:
	
	@Override
	public String image(IEObjectDescription description) {
		return description.getEClass().getName() + ".gif"; 
	}

}
