/*
 * generated by Xtext
 */
package fr.chaunier.xtext.mapdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MapDslRuntimeModule extends fr.chaunier.xtext.mapdsl.AbstractMapDslRuntimeModule {

}
