/*
* generated by Xtext
*/
package fr.chaunier.xtext.omc.ui.outline;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.outline.impl.DocumentRootNode;

import fr.chaunier.xtext.omc.omcDsl.Feature;

/**
 * customization of the default outline structure
 * 
 */
public class OmcDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	@Override
	protected void _createChildren(DocumentRootNode parentNode, EObject rootElement) {
		for (EObject content : rootElement.eContents()) {
			createNode(parentNode, content);
		}
	}

	protected boolean _isLeaf(Feature feature) {
		return true;
	}
	
}
