<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mapDsl"
    nsURI="http://www.chaunier.fr/xtext/map/MapDsl" nsPrefix="mapDsl">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="ecore:EClass platform:/resource/fr.chaunier.xtext.map/src-gen/fr/chaunier/xtext/map/MapDsl.ecore#//Import"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="ecore:EClass platform:/resource/fr.chaunier.xtext.map/src-gen/fr/chaunier/xtext/map/MapDsl.ecore#//Rule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fuctions" upperBound="-1"
        eType="ecore:EClass platform:/resource/fr.chaunier.xtext.map/src-gen/fr/chaunier/xtext/map/MapDsl.ecore#//Fuction"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappingModules" upperBound="-1"
        eType="ecore:EClass platform:/resource/fr.chaunier.xtext.map/src-gen/fr/chaunier/xtext/map/MapDsl.ecore#//MappingModule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roots" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.map/src-gen/fr/chaunier/xtext/map/MapDsl.ecore#//RootModule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RootModule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootRef" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.map/src-gen/fr/chaunier/xtext/map/MapDsl.ecore#//MappingModule"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="args" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fuction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="in" upperBound="-1" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.map/src-gen/fr/chaunier/xtext/map/MapDsl.ecore#//FuctionIn"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="out" upperBound="-1" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.map/src-gen/fr/chaunier/xtext/map/MapDsl.ecore#//FuctionOut"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuctionIn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inEntity" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.omcst.om/src-gen/fr/chaunier/xtext/omcst/om/OmcstDsl.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inAttribute" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.omcst.om/src-gen/fr/chaunier/xtext/omcst/om/OmcstDsl.ecore#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuctionOut">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outEntity" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.omcst.om/src-gen/fr/chaunier/xtext/omcst/om/OmcstDsl.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outAttribute" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.omcst.om/src-gen/fr/chaunier/xtext/omcst/om/OmcstDsl.ecore#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingModule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entitySource" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.omcst.om/src-gen/fr/chaunier/xtext/omcst/om/OmcstDsl.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityTarget" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.omcst.om/src-gen/fr/chaunier/xtext/omcst/om/OmcstDsl.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappedFeatures" upperBound="-1"
        eType="ecore:EClass platform:/resource/fr.chaunier.xtext.map/src-gen/fr/chaunier/xtext/map/MapDsl.ecore#//FeatureMap"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureMap">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fuctionMap" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.map/src-gen/fr/chaunier/xtext/map/MapDsl.ecore#//Fuction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeSource" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.omcst.om/src-gen/fr/chaunier/xtext/omcst/om/OmcstDsl.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeTarget" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.omcst.om/src-gen/fr/chaunier/xtext/omcst/om/OmcstDsl.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="withModule" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.map/src-gen/fr/chaunier/xtext/map/MapDsl.ecore#//MappingModule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeSources" unique="false"
        upperBound="-1" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.omcst.om/src-gen/fr/chaunier/xtext/omcst/om/OmcstDsl.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.map/src-gen/fr/chaunier/xtext/map/MapDsl.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.map/src-gen/fr/chaunier/xtext/map/MapDsl.ecore#//Rule"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NestedInTransformationParameter" eSuperTypes="platform:/resource/fr.chaunier.xtext.map/src-gen/fr/chaunier/xtext/map/MapDsl.ecore#//FuctionIn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.map/src-gen/fr/chaunier/xtext/map/MapDsl.ecore#//FuctionIn"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inRefAttribute" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.omcst.om/src-gen/fr/chaunier/xtext/omcst/om/OmcstDsl.ecore#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NestedOutTransformationParameter" eSuperTypes="platform:/resource/fr.chaunier.xtext.map/src-gen/fr/chaunier/xtext/map/MapDsl.ecore#//FuctionOut">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.map/src-gen/fr/chaunier/xtext/map/MapDsl.ecore#//FuctionOut"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outRefAttribute" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.omcst.om/src-gen/fr/chaunier/xtext/omcst/om/OmcstDsl.ecore#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NestedTransformationParameter" eSuperTypes="platform:/resource/fr.chaunier.xtext.map/src-gen/fr/chaunier/xtext/map/MapDsl.ecore#//FeatureMap">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.map/src-gen/fr/chaunier/xtext/map/MapDsl.ecore#//FeatureMap"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refAttribute" eType="ecore:EClass platform:/resource/fr.chaunier.xtext.omcst.om/src-gen/fr/chaunier/xtext/omcst/om/OmcstDsl.ecore#//Attribute"/>
  </eClassifiers>
</ecore:EPackage>
