/*
* generated by Xtext
*/
package fr.chaunier.xtext.archi.ui.contentassist;

import fr.chaunier.xtext.archi.ui.contentassist.AbstractAdslDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class AdslDslProposalProvider extends AbstractAdslDslProposalProvider {

}
