/*
 * generated by Xtext
 */
package fr.chaunier.xtext.bom;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BomDslRuntimeModule extends fr.chaunier.xtext.bom.AbstractBomDslRuntimeModule {

}
