/*
 * generated by Xtext
 */
package fr.chaunier.xtext.om;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class OmDslRuntimeModule extends fr.chaunier.xtext.om.AbstractOmDslRuntimeModule {

}
