/*
 * generated by Xtext
 */
package fr.chaunier.xtext.xgen.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XgenDslUiModule extends fr.chaunier.xtext.xgen.ui.AbstractXgenDslUiModule {
	public XgenDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
