/*
* generated by Xtext
*/
package fr.chaunier.xtext.instance.ui.contentassist;

import fr.chaunier.xtext.instance.ui.contentassist.AbstractInstDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class InstDslProposalProvider extends AbstractInstDslProposalProvider {

}
