/*
* generated by Xtext
*/
package fr.chaunier.xtext.constraint;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CstDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.chaunier.xtext.constraint.ui.internal.CstDslActivator.getInstance().getInjector("fr.chaunier.xtext.constraint.CstDsl");
	}
	
}
